# Generated by Django 5.0.6 on 2024-06-15 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_delete_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='description',
            new_name='recipe_description',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='image',
            new_name='recipe_image',
        ),
        migrations.RenameField(
            model_name='receipe',
            old_name='name',
            new_name='recipe_name',
        ),
    ]
