# Generated by Django 5.0.6 on 2024-06-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='recipie_view_cout',
            field=models.IntegerField(default=1),
        ),
    ]
