# Generated by Django 5.0.6 on 2024-06-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_receipe_recipie_view_cout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='recipie_view_cout',
            field=models.IntegerField(default=0),
        ),
    ]
